application:
  linkspravapi: http://localhost:9999/api/
  token: token
  botName: "@AvpermTestBot"
logging:
  level:
    root: DEBUG  #WARN
    logging.level.org.hibernate.SQL: DEBUG
    logging.level.org.hibernate.type.descriptor.sql: trace
  file:
    name: log/app.log
    max-size: 10MB
    max-history: 50
feign:
  client:
    config:
      BusSpravClient:
        connect-timeout: 5000
        read-timeout: 5000
        loggerLevel: full
  httpclient:
    disableSslValidation: true

